[package]
name = "fusion-search"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.1"
base64 = "0.21.5"
futures = "0.3.30"
lazy_static = "1.4.0"
mime = "0.3.17"
rand = "0.8.5"
reqwest = { version = "0.11.23", features = ["json"] }
scraper = "0.18.1"
tokio = "1.35.1"
url = "2.5.0"
