[package]
name = "fusion-search"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.1"
log = "0.4.20"
mime = "0.3.17"
reqwest = { version = "0.11.23", features = ["json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
