[package]
name = "fusion-search"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.1"
futures = "0.3.30"
lazy_static = "1.4.0"
mime = "0.3.17"
rand = "0.8.5"
regex = "1.10.2"
reqwest = { version = "0.11.23", features = ["json"] }
tokio = "1.35.1"
url = "2.5.0"
